/* Auto-generated no-op/zeroed stubs for removed subsystems. */
/* Generated by source/new/gen_stubs.py -- do not edit by hand. */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif
#include "doomstat.h"
#include "dsda.h"
#include "dsda/mapinfo/doom/parser.h"
#include "dsda/udmf.h"
#include "dsda/mapinfo.h"
#include "dsda/mapinfo/doom.h"
#include "dsda/mapinfo/u.h"
#include "dsda/utility.h"
#include "dsda/text_file.h"
#include "dsda/split_tracker.h"
#include "d_main.h"
#include "d_player.h"
#include "p_inter.h"
#include "p_user.h"
#include "r_defs.h"
#include "r_state.h"
#include "r_main.h"
#include "r_draw.h"
#include "r_patch.h"
#include "r_bsp.h"
#include "r_plane.h"
#include "r_segs.h"
#include "r_sky.h"
#include "p_spec.h"
#include "p_mobj.h"
#include "m_menu.h"
#include "sounds.h"
#include "s_sound.h"
#include "s_advsound.h"
#include "v_video.h"
#include "st_stuff.h"
#include "st_lib.h"
#include "hu_stuff.h"
#include "hu_lib.h"
#include "am_map.h"
#include "wi_stuff.h"
#include "f_finale.h"
#include "f_wipe.h"
#include "dsda/exhud.h"
#include "dsda/render_stats.h"
#include "dsda/palette.h"
#include "dsda/stretch.h"
#include "umapinfo.h"
#include "dsda/ambient.h"
#include "m_cheat.h"
#include "dsda/analysis.h"
#include "dsda/ghost.h"
#include "dsda/brute_force.h"
#include "dsda/build.h"
#include "dsda/tracker.h"
#include "dsda/console.h"
#include "dsda/messenger.h"
#include "dsda/wad_stats.h"
#include "dsda/episode.h"
#include "md5.h"
#include "hexen/po_man.h"
#include "hexen/p_acs.h"
#include "hexen/sn_sonix.h"
#include "hexen/p_things.h"
#include "hexen/in_lude.h"
#include "hexen/f_finale.h"
#include "hexen/p_anim.h"
#include "hexen/a_action.h"
#include "heretic/mn_menu.h"
#include "heretic/f_finale.h"
#include "heretic/in_lude.h"
#include "heretic/sb_bar.h"

void AM_Drawer(dboolean a0) { }
void AM_InitParams(void) { }
dboolean AM_Responder(event_t * a0) { static dboolean _r; return _r; }
void AM_Start(dboolean a0) { }
void AM_Stop(dboolean a0) { }
void AM_Ticker(void) { }
void AM_clearMarks(void) { }
void AM_initPlayerTrail(void) { }
void AM_setMarkParams(int a0) { }
void AM_updatePlayerTrail(fixed_t a0, fixed_t a1) { }
dboolean A_LocalQuake(byte * a0, mobj_t * a1) { static dboolean _r; return _r; }
void CheckACSPresent(int a0) { }
void D_InitFakeNetGame(void) { }
dboolean EV_MovePoly(line_t * a0, byte * a1, dboolean a2, dboolean a3) { static dboolean _r; return _r; }
dboolean EV_MovePolyTo(line_t * a0, int a1, fixed_t a2, fixed_t a3, fixed_t a4, dboolean a5) { static dboolean _r; return _r; }
dboolean EV_MoveZDoomPoly(line_t * a0, int a1, int a2, int a3, int a4, dboolean a5, dboolean a6) { static dboolean _r; return _r; }
dboolean EV_OpenPolyDoor(line_t * a0, byte * a1, podoortype_t a2) { static dboolean _r; return _r; }
dboolean EV_OpenZDoomPolyDoor(line_t * a0, int a1, int a2, int a3, int a4, int a5, podoortype_t a6) { static dboolean _r; return _r; }
dboolean EV_RotatePoly(line_t * a0, byte * a1, int a2, dboolean a3) { static dboolean _r; return _r; }
dboolean EV_RotateZDoomPoly(line_t * a0, int a1, int a2, int a3, int a4, dboolean a5) { static dboolean _r; return _r; }
dboolean EV_StopPoly(int a0) { static dboolean _r; return _r; }
dboolean EV_ThingActivate(int a0) { static dboolean _r; return _r; }
dboolean EV_ThingDeactivate(int a0) { static dboolean _r; return _r; }
dboolean EV_ThingDestroy(int a0) { static dboolean _r; return _r; }
dboolean EV_ThingProjectile(byte * a0, dboolean a1) { static dboolean _r; return _r; }
dboolean EV_ThingRemove(int a0) { static dboolean _r; return _r; }
dboolean EV_ThingSpawn(byte * a0, dboolean a1) { static dboolean _r; return _r; }
void F_BunnyScroll(void) { }
void F_Drawer(void) { }
dboolean F_Responder(event_t * a0) { static dboolean _r; return _r; }
void F_StartCast(const char * a0, const char * a1, dboolean a2) { }
void F_StartFinale(void) { }
void F_StartPostFinale(void) { }
void F_StartScroll(const char * a0, const char * a1, const char * a2, dboolean a3) { }
void F_TextWrite(void) { }
void F_Ticker(void) { }
void FakeNetUpdate(void) { }
float Get_TextSpeed(void) { static float _r; return _r; }
dboolean HU_CrosshairEnabled(void) { static dboolean _r; return _r; }
void HU_Drawer(void) { }
void HU_InitCrosshair(void) { }
void HU_InitThresholds(void) { }
dboolean HU_Responder(event_t * a0) { static dboolean _r; return _r; }
void HU_Start(void) { }
void HU_Ticker(void) { }
void I_CapturePrep(const char * a0) { }
void I_FinishUpdate(void) { }
int I_GetSfxLumpNum(sfxinfo_t * a0) { static int _r; return _r; }
void I_InitGraphics(void) { }
void I_InitMouse(void) { }
void I_InitScreenResolution(void) { }
void I_InitSound(void) { }
void I_InitSoundParams(void) { }
void I_PreInitGraphics(void) { }
void I_QueueFrameCapture(void) { }
void I_ResetMusicVolume(void) { }
int I_ScreenShot(const char * a0) { static int _r; return _r; }
void I_StartFrame(void) { }
void I_StartTic(void) { }
dboolean I_WindowFocused(void) { static dboolean _r; return _r; }
const char * LevelNames[54];
void LinkPolyobj(polyobj_t * a0) { }
void MD5Final(unsigned char a0[16], struct MD5Context * a1) { }
void MD5Init(struct MD5Context * a0) { }
void MD5Update(struct MD5Context * a0, const unsigned char * a1, unsigned int a2) { }
void MN_DrawPause(void) { }
void M_AutoSave(void) { }
void M_ChangeApplyPalette(void) { }
void M_ChangeDemoSmoothTurns(void) { }
void M_ChangeFullScreen(void) { }
void M_ChangeMIDIPlayer(void) { }
void M_ChangeMapMultisamling(void) { }
void M_ChangeMapTextured(void) { }
void M_ChangeVideoMode(void) { }
void M_CheatGod(void) { }
void M_CheatNoClip(void) { }
void M_DrawCredits(void) { }
void M_Drawer(void) { }
void M_ForcedLoadGame(const char * a0) { }
void M_Init(void) { }
dboolean M_Responder(event_t * a0) { static dboolean _r; return _r; }
void M_Ticker(void) { }
void MusInfoThinker(mobj_t * a0) { }
dboolean PO_Detect(int a0) { static dboolean _r; return _r; }
void PO_Init(int a0) { }
void PO_LoadThings(int a0) { }
void PO_LoadUDMFThings(int a0) { }
void PO_ResetBlockMap(dboolean a0) { }
void P_AnimateCompatibleSurfaces(void) { }
void P_AnimateHereticSurfaces(void) { }
void P_AnimateHexenSurfaces(void) { }
void P_AnimateSurfaces(void) { }
void P_AnimateZDoomSurfaces(void) { }
void P_ForceLightning(void) { }
void P_InitFTAnims(void) { }
void P_InitLightning(void) { }
void P_LoadACScripts(int a0) { }
void P_SpawnDirt(mobj_t * a0, fixed_t a1) { }
dboolean P_StartACS(int a0, int a1, byte * a2, mobj_t * a3, line_t * a4, int a5) { static dboolean _r; return _r; }
dboolean P_StartLockedACS(line_t * a0, byte * a1, mobj_t * a2, int a3) { static dboolean _r; return _r; }
dboolean P_SuspendACS(int a0, int a1) { static dboolean _r; return _r; }
void P_TagFinished(int a0) { }
dboolean P_TerminateACS(int a0, int a1) { static dboolean _r; return _r; }
int ParseUMapInfo(const unsigned char * a0, size_t a1, umapinfo_errorfunc a2) { static int _r; return _r; }
void R_CheckFuzzCol(int a0, int a1) { }
void R_ClearPlanes(void) { }
void R_DrawPlanes(void) { }
void R_DrawViewBorder(void) { }
void R_FillBackScreen(void) { }
visplane_t * R_FindPlane(fixed_t a0, int a1, int a2, int a3, fixed_t a4, fixed_t a5, angle_t a6, fixed_t a7, fixed_t a8) { static visplane_t * _r; return _r; }
dboolean R_FullView(void) { static dboolean _r; return _r; }
R_DrawColumn_f R_GetDrawColumnFunc(enum column_pipeline_e a0, enum draw_filter_type_e a1) { static R_DrawColumn_f _r; return _r; }
int R_GetFuzzPos(void) { static int _r; return _r; }
const rcolumn_t * R_GetPatchColumnClamped(const rpatch_t * a0, int a1) { static const rcolumn_t * _r; return _r; }
void R_InitBuffer(int a0, int a1) { }
void R_InitPatches(void) { }
void R_InitPlanes(void) { }
void R_InitSkyMap(void) { }
void R_InitTranslationTables(void) { }
int R_NumPatchWidth(int a0) { static int _r; return _r; }
dboolean R_PartialView(void) { static dboolean _r; return _r; }
const rpatch_t * R_PatchByNum(int a0) { static const rpatch_t * _r; return _r; }
void R_RenderMaskedSegRange(drawseg_t * a0, int a1, int a2) { }
void R_ResetAfterTeleport(player_t * a0) { }
void R_ResetColumnBuffer(void) { }
void R_ResetFuzzCol(int a0) { }
void R_SetDefaultDrawColumnVars(draw_column_vars_t * a0) { }
void R_SetFuzzPos(int a0) { }
void R_SmoothPlaying_Add(int a0) { }
angle_t R_SmoothPlaying_Get(player_t * a0) { static angle_t _r; return _r; }
void R_SmoothPlaying_Reset(player_t * a0) { }
void R_StoreWallRange(const int a0, const int a1) { }
void ResetPolySubSector(polyobj_t * a0) { }
void SB_PaletteFlash(dboolean a0) { }
void SB_SetClassData(void) { }
void SB_Start(void) { }
void SN_ChangeNodeData(int a0, int a1, int a2, int a3, int a4) { }
int SN_GetSequenceOffset(int a0, int * a1) { static int _r; return _r; }
void SN_InitSequenceScript(void) { }
void SN_StartSequence(mobj_t * a0, int a1) { }
void SN_StopAllSequences(void) { }
void SN_StopSequence(mobj_t * a0) { }
void ST_Drawer(dboolean a0) { }
void ST_Init(void) { }
dboolean ST_Responder(event_t * a0) { static dboolean _r; return _r; }
void ST_Start(void) { }
void ST_Ticker(void) { }
void SV_MapTeleport(int a0, int a1) { }
void SV_RestoreMapArchive(void) { }
void SV_StoreMapArchive(void) { }
void S_ChangeMusInfoMusic(int a0, int a1) { }
dboolean S_GetSoundPlayingInfo(void * a0, int a1) { static dboolean _r; return _r; }
void S_Init(void) { }
void S_LoopSectorSound(sector_t * a0, int a1, int a2) { }
void S_ParseMusInfo(const char * a0) { }
void S_PauseSound(void) { }
void S_ResetSfxVolume(void) { }
void S_ResetVolume(void) { }
void S_ResumeSound(void) { }
void S_Start(void) { }
void S_StartAmbientSound(void * a0, int a1, int a2) { }
void S_StartLineSound(line_t * a0, degenmobj_t * a1, int a2) { }
void S_StartMobjSound(mobj_t * a0, int a1) { }
void S_StartMusic(int a0) { }
void S_StartSectorSound(sector_t * a0, int a1) { }
void S_StartSound(void * a0, int a1) { }
void S_StartVoidSound(int a0) { }
void S_StopMusic(void) { }
void S_StopSound(void * a0) { }
void S_StopSoundLoops(void) { }
void S_UnlinkSound(void * a0) { }
void S_UpdateSounds(void) { }
int SetCustomMessage(int a0, const char * a1, int a2, int a3) { static int _r; return _r; }
void SetRatio(int a0, int a1) { }
void T_InterpretACS(acs_t * a0) { }
void T_MAPMusic(void) { }
void T_MovePoly(polyevent_t * a0) { }
void T_PolyDoor(polydoor_t * a0) { }
void T_RotatePoly(polyevent_t * a0) { }
void TryRunTics(void) { }
void UnLinkPolyobj(polyobj_t * a0) { }
V_BeginUIDraw_f V_BeginUIDraw;
int V_BloodColor(int a0) { static int _r; return _r; }
void V_ChangeScreenResolution(void) { }
void V_ClearBorder(void) { }
V_DrawNumPatch_f V_DrawNumPatch;
void V_DrawRawScreen(const char * a0) { }
V_EndUIDraw_f V_EndUIDraw;
V_FillRect_f V_FillRect;
void V_FreePlaypal(void) { }
void V_Init(void) { }
void V_InitColorTranslation(void) { }
dboolean V_IsOpenGLMode(void) { static dboolean _r; return _r; }
dboolean V_IsSoftwareMode(void) { static dboolean _r; return _r; }
void V_SetPalette(int a0) { }
void WI_Drawer(void) { }
void WI_End(void) { }
void WI_Start(wbstartstruct_t * a0) { }
void WI_Ticker(void) { }
void WI_checkForAccelerate(void) { }
int capturing_video;
cheatseq_t cheat[76];
int demo_smoothturnsfactor;
fixed_t * distscale;
musicinfo_t doom_S_music[69];
sfxinfo_t doom_S_sfx[700];
doom_mapinfo_t doom_mapinfo;
dboolean dsda_100k;
dboolean dsda_100k_note_shown;
dboolean dsda_100k_on_map;
dboolean dsda_100s;
void dsda_AddCommandToCommandDisplay(ticcmd_t * a0) { }
void dsda_AddCustomEpisodes(void) { }
void dsda_AddMessage(const char * a0) { }
void dsda_AddOriginalEpisodes(void) { }
void dsda_AddPlayerMessage(const char * a0, player_t * a1) { }
void dsda_AddSplit(dsda_split_class_t a0, int a1) { }
dboolean dsda_AdvanceFrame(void) { static dboolean _r; return _r; }
dboolean dsda_AllowCasualExCmdFeatures(void) { static dboolean _r; return _r; }
dboolean dsda_AllowExCmd(void) { static dboolean _r; return _r; }
dboolean dsda_AllowFreeLook(void) { static dboolean _r; return _r; }
dboolean dsda_AllowJumping(void) { static dboolean _r; return _r; }
void dsda_ApplyDSDADemoFormat(byte ** a0) { }
void dsda_ApplyQuickstartMouseCache(int * a0) { }
void dsda_ArchiveMusic(void) { }
void dsda_AttachPlaybackStream(const byte * a0, int a1, int a2) { }
void dsda_BeginRenderStats(void) { }
dboolean dsda_BruteForce(void) { static dboolean _r; return _r; }
dboolean dsda_BruteForceEnded(void) { static dboolean _r; return _r; }
dboolean dsda_BuildMode(void) { static dboolean _r; return _r; }
dboolean dsda_BuildResponder(event_t * a0) { static dboolean _r; return _r; }
void dsda_CacheEndoom(void) { }
dboolean dsda_CameraPaused(void) { static dboolean _r; return _r; }
void dsda_ClearPlaybackStream(void) { }
int dsda_ColorNameToIndex(const char * a0) { static int _r; return _r; }
int dsda_CopyExDemo(const byte ** a0, int * a1) { static int _r; return _r; }
char * dsda_DataDir(void) { static char * _r; return _r; }
int dsda_DemoAttempts(void) { static int _r; return _r; }
int dsda_DemoTicsCount(const byte * a0, const byte * a1, int a2) { static int _r; return _r; }
char * dsda_DetectDirectory(const char * a0, int a1) { static char * _r; return _r; }
void dsda_DisableExCmd(void) { }
void dsda_DumpEndoom(void) { }
void dsda_EndDemoRecording(void) { }
void dsda_EnterBuildMode(void) { }
void dsda_EvaluateBruteForce(void) { }
void dsda_EvaluateBytesPerTic(void) { }
const byte * dsda_EvaluateDemoStartPoint(const byte * a0) { static const byte * _r; return _r; }
void dsda_EvaluateSkipModeBuildTiccmd(void) { }
void dsda_EvaluateSkipModeCheckDemoStatus(void) { }
void dsda_EvaluateSkipModeDoCompleted(void) { }
void dsda_EvaluateSkipModeDoTeleportNewMap(void) { }
void dsda_EvaluateSkipModeDoWorldDone(void) { }
void dsda_EvaluateSkipModeGTicker(void) { }
void dsda_EvaluateSkipModeInitNew(void) { }
void dsda_ExecutePlaybackOptions(void) { }
void dsda_ExportGhostFrame(void) { }
void dsda_ExportTextFile(void) { }
dboolean dsda_FreeAim(void) { static dboolean _r; return _r; }
void dsda_FreeDehMusic(void) { }
void dsda_FreeDehSFX(void) { }
int dsda_GetDehMusicIndex(const char * a0, size_t a1) { static int _r; return _r; }
sfxinfo_t * dsda_GetDehSFX(int a0) { static sfxinfo_t * _r; return _r; }
int dsda_GetDehSFXIndex(const char * a0, size_t a1) { static int _r; return _r; }
int dsda_GetOriginalMusicIndex(const char * a0) { static int _r; return _r; }
int dsda_GetOriginalSFXIndex(const char * a0) { static int _r; return _r; }
void dsda_HandleMapPreferences(void) { }
void dsda_HandleSkip(void) { }
int dsda_HexenAirControl(fixed_t * a0) { static int _r; return _r; }
int dsda_HexenApplyFadeTable(void) { static int _r; return _r; }
int dsda_HexenBorderTexture(const char ** a0) { static int _r; return _r; }
int dsda_HexenBossAction(mobj_t * a0) { static int _r; return _r; }
int dsda_HexenEnterPic(const char ** a0) { static int _r; return _r; }
int dsda_HexenExitPic(const char ** a0) { static int _r; return _r; }
void dsda_HexenFDrawer(void) { }
int dsda_HexenFTicker(void) { static int _r; return _r; }
int dsda_HexenFirstMap(int * a0, int * a1) { static int _r; return _r; }
int dsda_HexenGravity(fixed_t * a0) { static int _r; return _r; }
int dsda_HexenHUTitle(dsda_string_t * a0) { static int _r; return _r; }
int dsda_HexenInitSky(void) { static int _r; return _r; }
int dsda_HexenInterMusic(int * a0, int * a1) { static int _r; return _r; }
int dsda_HexenIntermissionMusic(int * a0, int * a1) { static int _r; return _r; }
void dsda_HexenLoadMapInfo(void) { }
int dsda_HexenMapAuthor(const char ** a0) { static int _r; return _r; }
int dsda_HexenMapCluster(int * a0, int a1) { static int _r; return _r; }
int dsda_HexenMapColorMap(int * a0) { static int _r; return _r; }
int dsda_HexenMapFlags(map_info_flags_t * a0) { static int _r; return _r; }
int dsda_HexenMapLightning(int * a0) { static int _r; return _r; }
int dsda_HexenMapLumpName(const char ** a0, int a1, int a2) { static int _r; return _r; }
int dsda_HexenMapMusic(int * a0, int * a1, int a2, int a3) { static int _r; return _r; }
int dsda_HexenMusicIndexToLumpNum(int * a0, int a1) { static int _r; return _r; }
int dsda_HexenNameToMap(int * a0, const char * a1, int * a2, int * a3) { static int _r; return _r; }
int dsda_HexenNewGameMap(int * a0, int * a1) { static int _r; return _r; }
int dsda_HexenNextMap(int * a0, int * a1) { static int _r; return _r; }
int dsda_HexenPrepareEntering(void) { static int _r; return _r; }
int dsda_HexenPrepareFinale(int * a0) { static int _r; return _r; }
int dsda_HexenPrepareFinished(void) { static int _r; return _r; }
int dsda_HexenPrepareInitNew(void) { static int _r; return _r; }
int dsda_HexenPrepareIntermission(int * a0) { static int _r; return _r; }
int dsda_HexenPrevMap(int * a0, int * a1) { static int _r; return _r; }
int dsda_HexenResolveCLEV(int * a0, int * a1, int * a2) { static int _r; return _r; }
int dsda_HexenResolveINIT(int * a0) { static int _r; return _r; }
int dsda_HexenResolveWarp(int * a0, int a1, int * a2, int * a3) { static int _r; return _r; }
int dsda_HexenShowNextLocBehaviour(int * a0) { static int _r; return _r; }
int dsda_HexenSkipDrawShowNextLoc(int * a0) { static int _r; return _r; }
int dsda_HexenSky1Texture(short * a0) { static int _r; return _r; }
int dsda_HexenSky2Texture(short * a0) { static int _r; return _r; }
int dsda_HexenSkyTexture(int * a0) { static int _r; return _r; }
int dsda_HexenStartFinale(void) { static int _r; return _r; }
void dsda_HexenUpdateLastMapInfo(void) { }
void dsda_HexenUpdateMapInfo(void) { }
void dsda_HexenUpdateNextMapInfo(void) { }
void dsda_InitCommandHistory(void) { }
void dsda_InitDemoPlayback(void) { }
void dsda_InitDemoRecording(void) { }
void dsda_InitExHud(void) { }
void dsda_InitFont(void) { }
void dsda_InitGameController(void) { }
void dsda_InitGameControllerParameters(void) { }
void dsda_InitGhostExport(const char * a0) { }
void dsda_InitGhostImport(const char ** a0, int a1) { }
void dsda_InitMessenger(void) { }
void dsda_InitParallelSFXFilter(void) { }
void dsda_InitQuickstartCache(void) { }
void dsda_InitializeMusic(musicinfo_t * a0, int a1) { }
void dsda_InitializeSFX(sfxinfo_t * a0, int a1) { }
void dsda_InterpretConsoleCommands(const char * a0, dboolean a1, dboolean a2) { }
void dsda_JoinDemoCmd(ticcmd_t * a0) { }
void dsda_LoadExDemo(const char * a0) { }
void dsda_LoadSndInfo(void) { }
void dsda_LoadWadPreferences(void) { }
void dsda_MarkCompatibilityLevelUnspecified(void) { }
int dsda_MaskPause(void) { static int _r; return _r; }
void dsda_MergeFeatures(uint64_t a0) { }
void dsda_ParseDoomMapInfo(const unsigned char * a0, size_t a1, doom_mapinfo_errorfunc a2) { }
const char * dsda_ParsePlaybackOptions(void) { static const char * _r; return _r; }
void dsda_ParseUDMF(const unsigned char * a0, size_t a1, udmf_errorfunc a2) { }
dboolean dsda_PauseMode(int a0) { static dboolean _r; return _r; }
dboolean dsda_Paused(void) { static dboolean _r; return _r; }
dboolean dsda_PausedOutsideDemo(void) { static dboolean _r; return _r; }
dboolean dsda_PausedViaMenu(void) { static dboolean _r; return _r; }
dboolean dsda_PendingJoin(void) { static dboolean _r; return _r; }
const char * dsda_PlaybackName(void) { static const char * _r; return _r; }
int dsda_PlaybackTics(void) { static int _r; return _r; }
void dsda_PopExCmdQueue(ticcmd_t * a0) { }
void dsda_PreferOpenGL(void) { }
void dsda_QueueExCmdJump(void) { }
void dsda_QueueExCmdLoad(int a0) { }
void dsda_QueueExCmdLook(short a0) { }
void dsda_QueueExCmdSave(int a0) { }
void dsda_QueueJoin(void) { }
void dsda_QueueQuickstart(void) { }
void dsda_ReadBuildCmd(ticcmd_t * a0) { }
void dsda_ReadExCmd(ticcmd_t * a0, const byte ** a1) { }
void dsda_RecordSplit(void) { }
void dsda_RecordVisSprites(int a0) { }
void dsda_RefreshBuildMode(void) { }
void dsda_RefreshExHudCommandDisplay(void) { }
void dsda_RefreshExHudCoordinateDisplay(void) { }
void dsda_RefreshExHudFPS(void) { }
void dsda_RefreshExHudLevelSplits(void) { }
void dsda_RefreshExHudMinimap(void) { }
void dsda_RefreshMapCoordinates(void) { }
void dsda_RefreshMapTime(void) { }
void dsda_RefreshMapTitle(void) { }
void dsda_RefreshMapTotals(void) { }
void dsda_RemovePauseMode(int a0) { }
void dsda_ResetAnalysis(void) { }
void dsda_ResetCommandHistory(void) { }
void dsda_ResetExCmdQueue(void) { }
void dsda_ResetPauseMode(void) { }
void dsda_ResetSplits(void) { }
void dsda_ResetTrackers(void) { }
void dsda_RestartPlayback(void) { }
void dsda_RestoreCommandHistory(void) { }
void dsda_RestoreDemoData(byte a0) { }
void dsda_RestorePlaybackPosition(void) { }
void dsda_SaveWadStats(void) { }
void dsda_SetDemoBaseName(const char * a0) { }
void dsda_SetupStretchParams(void) { }
dboolean dsda_SkipMode(void) { static dboolean _r; return _r; }
void dsda_SpawnAmbientSource(mobj_t * a0) { }
void dsda_SpawnGhost(void) { }
void dsda_SpawnQuake(mobj_t * a0, int a1, int a2, int a3, int a4) { }
void dsda_StoreDemoData(byte a0) { }
void dsda_StorePlaybackPosition(void) { }
const byte * dsda_StripDemoVersion255(const byte * a0, const byte * a1, size_t a2) { static const byte * _r; return _r; }
void dsda_ToggleBuildTurbo(void) { }
void dsda_TogglePauseMode(int a0) { }
void dsda_TrackFeature(int a0) { }
void dsda_TryPlaybackOneTick(ticcmd_t * a0) { }
void dsda_UnArchiveMusic(void) { }
void dsda_UnmaskPause(int a0) { }
void dsda_UpdateAmbientSource(ambient_source_t * a0) { }
void dsda_UpdateBruteForce(void) { }
void dsda_UpdateFreeText(void) { }
void dsda_UpdateQuake(quake_t * a0) { }
void dsda_UpdateRenderStats(void) { }
dboolean dsda_UseMapinfo(void) { static dboolean _r; return _r; }
uint64_t dsda_UsedFeatures(void) { static uint64_t _r; return _r; }
void dsda_WriteAnalysis(void) { }
void dsda_WriteExCmd(char ** a0, ticcmd_t * a1) { }
void dsda_WriteSplits(void) { }
void dsda_WriteTicToDemo(const void * a0, size_t a1) { }
void dsda_WriteToDemo(const void * a0, size_t a1) { }
dboolean dsda_almost_reality;
dboolean dsda_almost_reality_note_shown;
dboolean dsda_any_counted_monsters;
dboolean dsda_any_monsters;
dboolean dsda_any_secrets;
dboolean dsda_any_weapons;
int dsda_kills_on_map;
int dsda_missed_monsters;
int dsda_missed_secrets;
int dsda_missed_weapons;
dboolean dsda_pacifist;
dboolean dsda_pacifist_note_shown;
dboolean dsda_reality;
dboolean dsda_reality_note_shown;
dboolean dsda_reborn;
dboolean dsda_stroller;
dboolean dsda_turbo;
dboolean dsda_tyson_weapons;
dboolean dsda_weapon_collector;
musicinfo_t heretic_S_music[53];
sfxinfo_t heretic_S_sfx[142];
const demostate_t heretic_demostates[8][4];
raven_mobjinfo_t heretic_mobjinfo[307];
const char * heretic_sprnames[129];
state_t heretic_states[1208];
musicinfo_t hexen_S_music[106];
sfxinfo_t hexen_S_sfx[245];
const demostate_t hexen_demostates[8][4];
raven_mobjinfo_t hexen_mobjinfo[706];
const char * hexen_sprnames[301];
state_t hexen_states[2846];
mapcolor_t mapcolor;
int markpointnum;
int markpointnum_max;
markpoint_t * markpoints;
int playerkeys;
int solo_net;
udmf_t udmf;
int wipe_EndScreen(void) { static int _r; return _r; }
int wipe_StartScreen(void) { static int _r; return _r; }
fixed_t * yslope;

/* resolved data + orphan inits */
acsInfo_t *ACSInfo;
acsstore_t ACSStore[MAX_ACS_STORE + 1];
int ACScriptCount;
int ActiveSequences;
animDef_t AnimDefs[MAX_ANIM_DEFS];
int ArtifactFlash;
int BorderNeedRefresh;
int LightningFlash;
int MapVars[MAX_ACS_MAP_VARS];
struct MapList Maps;
int NextLightningFlash;
polyblock_t** PolyBlockMap;
int ST_SCALED_HEIGHT;
musicinfo_t* S_music;
sfxinfo_t* S_sfx;
seqnode_t *SequenceListHead;
int Sky1Texture;
int WorldVars[MAX_ACS_WORLD_VARS];
int acceleratestage;
int automap_active;
int automap_follow;
int automap_grid;
int automap_overlay;
int automap_rotate;
int cap_fps;
int cap_frac;
int cap_wipescreen;
visplane_t       *ceilingplane;
const byte *colrngs[1];
int curpos;
int demo_smoothturns;
dboolean demoplayback;
int dsda_analysis;
int el_author;
int el_levelname;
int el_levelpic;
dsda_episode_t* episodes;
fake_contrast_mode_t fake_contrast_mode;
int finalecount;
int finaleflat;
int finalepatch;
int finalestage;
int finaletext;
visplane_t       *floorplane;
fixed_t freelookviewheight;
int full_sounds;
float gl_ratio;
patchnum_t grnrock;
int idmusnum;
int inhelpscreens;
int inv_ptr;
dboolean inventory;
int lf_author;
int lf_levelname;
int lf_levelpic;
int localQuakeHappening[MAX_MAXPLAYERS];
__STORAGE_MODIFIER ticcmd_t local_cmds[MAX_MAXPLAYERS];
const byte *main_tranmap;
int        maketic;
map_trail_mode_t map_trail_mode;
menuactive_t menuactive;
int midstage;
int mn_SuicideConsole;
int ms_to_next_tick;
musinfo_t musinfo;
size_t num_episodes;
int num_sfx;
byte playernumtotrans[MAX_MAXPLAYERS];
int playpal_black;
int playpal_white;
int po_NumPolyobjs;
polyobj_t *polyobjs;
int psprite_offset;
unsigned int ratio_multiplier;
unsigned int ratio_scale;
int render_stretch_hud;
int              rw_angle1;
int skyflatnum;
int skytexture;
int sts_always_red;
int sts_pct_always_gray;
int sts_traditional_keys;
dboolean tallscreen;
const byte *tranmap;
byte       *translationtables;
int          usegamma;
dboolean userdemo;
int      viewheight;
int      viewwidth;
const lighttable_t **walllights;
dboolean window_focused;
