#!/bin/bash
# Regenerate the new deglobalized DSDA-Doom core from the pristine base core.
#
# Reproducible pipeline:
#   1. rsync base/core -> new/core (clean copy of upstream headless dsda-doom)
#   2. (re)configure meson so compile_commands.json has new entries with exact flags
#   3. run the clang-AST deglobalizer over new/core's C TUs (--apply)
#      - excludes the immutable LUTs in exclude-symbols.txt
#      - cross-validates completeness against the base core's nm writable symbols
#   4. build newTester
#
# The savestate is intentionally NOT trimmed here (Phase 5 does that separately).
# C++-defined globals (MAPINFO/UMAPINFO/UDMF/ambient) are left shared, matching
# the hand-built core; the deglobalizer drops their extern decls automatically.
set -e

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
qd="$(cd "$here/../.." && pwd)"          # quickerDSDA root
base="$qd/source/base/core"
new="$qd/source/new/core"
build="$qd/build"

echo "[regen] 1/4 rsync base/core -> new/core"
rsync -a --delete --exclude='.git' "$base/" "$new/"

# new/meson.build references __headless_stubs.c (generated later); rsync --delete
# just wiped it, so meson would fail to configure. Create a placeholder now.
printf '/* placeholder; regenerated by make_headless_stubs.py */\n' > "$new/prboom2/src/__headless_stubs.c"

echo "[regen] 1b/4 annotate code-generating macros (globals the AST tool can't reach)"
# IMPLEMENT_BLOCK_MEMORY_ALLOC_ZONE expands to a file-scope global definition
# (e.g. secnodezone). The deglobalizer can only see the macro-expanded VarDecl
# (empty tokens), so the block-zone pool must be made thread-local at the macro
# DEFINITION, else all threads share one allocator pool -> heap corruption.
bmalloc="$new/prboom2/src/z_bmalloc.h"
# Annotate BOTH the definition (IMPLEMENT) and the extern declaration (DECLARE)
# so the thread-local attribute is consistent.
sed -i 's/^struct block_memory_alloc_s name = { NULL, size, num, desc}/__STORAGE_MODIFIER struct block_memory_alloc_s name = { NULL, size, num, desc}/' "$bmalloc"
sed -i 's/#define DECLARE_BLOCK_MEMORY_ALLOC_ZONE(name) extern struct block_memory_alloc_s name/#define DECLARE_BLOCK_MEMORY_ALLOC_ZONE(name) extern __STORAGE_MODIFIER struct block_memory_alloc_s name/' "$bmalloc"

# local_cmds: per-instance ticcmd buffer is harness-owned (emuInstanceBase declares
# it __thread for per-thread savestate). Its definition lived in the now-removed
# d_client.c; tag the doomstat.h extern decl thread-local so all core references
# match the harness, and let make_headless_stubs.py define it (MANUAL map).
sed -i 's/^extern  ticcmd_t   local_cmds\[\];/extern __STORAGE_MODIFIER ticcmd_t   local_cmds[];/' "$new/prboom2/src/doomstat.h"

# Phase 6 (serialization speed): dsda_UnArchiveAll re-runs G_InitNew on every state
# restore -- a full P_SetupLevel map reload -- then the archive overwrites it. In
# single-player headless search the level is already loaded and the archive restores
# all mutable state, so the reload is pure waste (~73x slower restores). Skip it.
sed -i 's@^  G_InitNew(gameskill, gameepisode, gamemap, false);@  /* [min-headless] skip redundant per-restore level reload; archive restores state */ /* G_InitNew(gameskill, gameepisode, gamemap, false); */@' "$new/prboom2/src/dsda/save.c"

echo "[regen] 2/4 reconfigure meson (compile_commands.json)"
meson setup "$build" --reconfigure -DonlyFree=false >/dev/null

echo "[regen] 3a/4 derive base nm writable-symbol baseline (for completeness check)"
globals="$build/base_c_globals.txt"
: > "$globals"
for o in $(find "$build" -path '*baseTester.p*' -name '*.c.o' | grep -v source_tester); do
  nm "$o" 2>/dev/null | grep -E '^[0-9a-f]* [BbDd] ' >> "$globals" || true
done

echo "[regen] 3b/4 run clang-AST deglobalizer (--apply)"
python3 "$here/deglobalize.py" \
  --compile-commands "$build/compile_commands.json" \
  --root "$new" \
  --exclude-symbols "$here/exclude-symbols.txt" \
  --nm-symbols "$globals" \
  --apply

echo "[regen] 3c/5 apply physics-neutral source neuters (precache/sprite-init)"
# These early-return pure-display functions in KEPT files that would otherwise
# crash once their (removed) subsystem data tables are gone. rsync --delete above
# wiped them, so re-apply (idempotent).
python3 "$here/apply_headless_neuters.py" "$new/prboom2/src"

echo "[regen] 3d/5 apply canonical-serialization patches (Design A)"
# Make the savestate byte-canonical (zero allocation-dependent pointer fields +
# save boom/true basetic directly). Required for cross-thread dedup and a future
# zone-snapshot; verified by tTester2 --strict. Idempotent; applied to the kept
# p_saveg.c / dsda/save.c that rsync --delete wiped above.
python3 "$here/apply_canonical_serialization.py" "$new/prboom2/src"

echo "[regen] 3e/5 apply mobj savestate-size trim (Design B state reduction)"
# Reorder mobj_t so the cl2-Doom2 gameplay fields form a saved prefix and the
# render/Heretic-Hexen/respawn/transient fields form an unsaved tail, and serialize
# only the prefix (~34% smaller state). Generated as a diff against the canonical-
# patched p_saveg.c + pristine p_mobj.h, so it applies right after step 3d.
patch -p1 -d "$qd" < "$here/state_trim.patch"

echo "[regen] 4/5 generate minimal-headless stubs (__headless_stubs.c)"
# The kept simulation code references symbols from the removed display/sound/
# non-Doom subsystems (source/new/removed_files.txt, commented out of
# new/meson.build). Generate no-op/zeroed stubs so the link is satisfied without
# pulling those subsystems in. Bit-exact for physics (verified per subsystem).
python3 "$here/make_headless_stubs.py"

echo "[regen] 5/5 build newTester + pTester"
rm -f "$build/newTester" "$build/pTester"   # avoid being fooled by stale binaries
ninja -C "$build" newTester pTester

echo "[regen] done (minimal headless Doom2 core)."
